version: '3'
services:
  api:
    tty: true
    image: node:10.13
    volumes:
      - .:/app:cached
      - ./node_modules:/app/node_modules:delegated
      - yarn-cache:/.yarn-cache
    working_dir: /app/services/api
    entrypoint: "yarn"
    command: ["start"]
    depends_on:
      - mongodb
    environment:
      YARN_CACHE_FOLDER: /.yarn-cache
      NODE_ENV: development
      MONGO_DSN: mongodb://mongodb:27017/wtq
    ports:
      - "8001:80"
  site:
    tty: true
    image: node:10.13
    volumes:
      - .:/app:cached
      - ./node_modules:/app/node_modules:delegated
      - yarn-cache:/.yarn-cache
    working_dir: /app/services/site
    entrypoint: ["node"]
    command: ["server.js"]
    depends_on:
      - api
    environment:
      YARN_CACHE_FOLDER: /.yarn-cache
      NODE_ENV: development
      GRAPHQL_URL: http://api
    ports:
      - "8002:80"

  mongodb:
    tty: true
    image: mongo:3.6
    volumes:
      - mongodb:/data/db
      - ./wtq-db:/wtq-db
    ports:
      - "8000:27017"
volumes:
  mongodb: {}
  yarn-cache: {}
